name: Build and upload binaries

on: workflow_dispatch

jobs:
  build:
    name: Build and upload

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config -y

      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - run: npm install --no-save prebuild
      - run: npm run prebuild
      - run: npx prebuild --upload-all ${{ secrets.GITHUB_TOKEN }}
